# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

name: 2.2.0$(Rev:.r)

trigger:
- master

pr:
- master
- releases/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: './example/**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  projectSource: './src'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: Npm@1
  displayName: npm install
  inputs:
    command: 'install'
    workingDir: '$(projectSource)'

- task: Npm@1
  displayName: npm install -g gulp
  inputs:
    command: 'custom'
    customCommand: 'install -g gulp-cli'

- task: Npm@1
  displayName: npm build
  inputs:
    command: 'custom'
    workingDir: '$(projectSource)'
    customCommand: 'run build'